window.Y5Q_CONTENT = {
  english: {
    label: 'English World', icon: '📚', theme: 'english',
    sections: [
      { title:'Kinds of Word', lesson:'Learn how different words do different jobs in sentences. The section builds recognition of nouns, pronouns, articles, adjectives, verbs, adverbs and prepositions.', topics:['Nouns','Pronouns','Articles','Adjectives','Verbs','Adverbs','Prepositions'], explain:'Create one sentence and identify at least three different word classes in it.' },
      { title:'Punctuation', lesson:'Use punctuation to make meaning clear: sentence endings, possession, missing letters, commas, extra information, direct speech, colons and semi-colons.', topics:['Sentence Punctuation','Showing Who Owns What','Showing Missing Letters with an Apostrophe',"It's and Its",'Commas — Lists and Long Sentences','Adding Extra Information','Inverted Commas','Colons and Semi-Colons'], explain:'Take a sentence without punctuation and explain what you would add and why.' },
      { title:'Writing Proper Sentences', lesson:'Build complete, accurate sentences using verbs, active and passive forms, comparisons, clauses and conjunctions.', topics:['Using Verbs in Sentences','Active and Passive Verbs','Comparing Things Properly','Clauses','Conjunctions'], explain:'Turn a simple sentence into a longer one by adding another clause.' },
      { title:'How to Use Paragraphs', lesson:'Organise related sentences into paragraphs. New events, speakers, people, places or times can signal a new paragraph.', topics:['Paragraphs Make Things Clear','When to Start a New Paragraph','New People and People Speaking','When the Place or Time Changes'], explain:'Explain why a new speaker in dialogue normally starts a new paragraph.' },
      { title:'Planning and Writing', lesson:'Plan before writing by identifying audience and purpose, developing ideas, drafting and improving the final piece.', topics:['How to Plan','Identifying Audience and Purpose','How to Develop Your Writing','Drafting and Improving Your Writing'], explain:'Explain how writing for a headteacher differs from writing to a close friend.' },
      { title:'Writing Stories', lesson:'Create stronger stories with effective openings, viewpoint, description, imagery, speech and varied vocabulary.', topics:['How to Start Your Story',"Who's Telling the Story",'Describing Things Well','Three Types of Image','Writing Speech','Using Varied Words'], explain:'Invent a character and explain how their speech could reveal their personality.' },
      { title:'Other Types of Writing', lesson:'Match writing style to purpose. Formal letters, informal letters and leaflets use different language and presentation choices.', topics:['Writing a Formal Letter','Using Formal Language','Writing an Informal Letter','Using Chatty Language','Writing Leaflets','Making Leaflets Persuasive'], explain:'Give one clear difference between formal and informal writing.' },
      { title:'Reading', lesson:'Read questions carefully, return to the text, find evidence and use clues to work out answers that are not stated directly.', topics:['Doing Reading Questions','Reading the Text','Working Out the Answers','How to Give a Good Answer','Questions that Ask What You Think','Reading Test — Story','Questions on the Story','More Questions on the Story','Reading Test — Poem','Questions on the Poem','Reading Test — Descriptions','Questions on Short Descriptions','Tricky Questions','More Tricky Questions'], explain:'Explain the difference between finding a fact and inferring an answer from clues.' },
      { title:'Confusing Words', lesson:'Choose accurately between words that sound or look similar by thinking about their meaning and grammatical job.', topics:['Practice / Practise and Advice / Advise','Affect / Effect and Passed / Past','To / Too / Two','Of / Off','Did / Done and Saw / Seen'], explain:'Use to, too and two correctly in one sentence.' },
      { title:'Handwriting and Spelling', lesson:'Improve written accuracy through handwriting, spelling rules, plural forms, prefixes, suffixes and vocabulary relationships.', topics:['Improving Handwriting','Spelling Rules',"When There's More Than One",'Prefixes and Suffixes','Synonyms and Antonyms','Difficult and Tricky Words'], explain:'Choose a word with a prefix or suffix and explain what that part adds to the meaning.' }
    ],
    questions: [
      {section:0,q:'Which word is the noun in “The enormous tiger moved quietly”?',a:['enormous','tiger','moved','quietly'],c:1,h:'Look for the word that names a thing or creature.',e:'“Tiger” names an animal, so it is the noun.'},
      {section:0,q:'Which word is the adverb in “Aisha answered politely”?',a:['Aisha','answered','politely','none'],c:2,h:'Find the word that tells us how the action happened.',e:'“Politely” tells us how Aisha answered.'},
      {section:1,q:'Which sentence is punctuated correctly as a question?',a:['Where are you going.','Where are you going?','where are you going?','Where are you going!'],c:1,h:'Check both the capital letter and the final punctuation mark.',e:'A question begins with a capital letter and ends with a question mark.'},
      {section:1,q:'Which sentence uses direct speech?',a:['Mia said that she was tired.','Leo said, “I am ready.”','Ben wondered whether it was raining.','The teacher explained the task.'],c:1,h:'Direct speech gives the exact words spoken.',e:'“I am ready” gives Leo’s exact words, so it is direct speech.'},
      {section:2,q:'In “The ball was kicked by Sam”, which voice is used?',a:['active','passive','imperative','question'],c:1,h:'Think about whether the subject performs the action or receives it.',e:'The ball receives the action, so the sentence is passive.'},
      {section:2,q:'Which word is a conjunction in “I wanted to play, but it began to rain”?',a:['wanted','play','but','rain'],c:2,h:'Find the word joining two ideas.',e:'“But” joins two contrasting clauses.'},
      {section:3,q:'Which change normally needs a new paragraph in dialogue?',a:['A new person speaks','A noun appears','A sentence is short','A word is repeated'],c:0,h:'Think about helping the reader follow who is talking.',e:'A new speaker normally begins a new paragraph.'},
      {section:4,q:'What should a writer identify before choosing language and style?',a:['Audience and purpose','Only the title','Paper colour','Number of commas'],c:0,h:'Think about who will read the writing and why it is being written.',e:'Audience and purpose guide tone, content and level of formality.'},
      {section:5,q:'Which feature can reveal what a story character is like?',a:['How the character speaks','Only the page number','The margin width','The font size'],c:0,h:'Think about dialogue.',e:'A character’s words and manner of speaking can reveal personality.'},
      {section:6,q:'Which opening best suits a formal letter when the recipient’s name is unknown?',a:['Hey mate!','Dear Sir or Madam,','Yo!','Hiya!'],c:1,h:'Choose the least casual greeting.',e:'“Dear Sir or Madam,” is an appropriate formal opening.'},
      {section:7,q:'Working out an answer from clues in a text is called what?',a:['Inference','Alphabetising','Copying','Handwriting'],c:0,h:'The answer is not stated directly.',e:'Inference means using clues and evidence to work something out.'},
      {section:8,q:'Choose the correct word: “I have ___ books on my desk.”',a:['to','too','two','off'],c:2,h:'The sentence needs a number.',e:'“Two” is the number 2.'},
      {section:8,q:'Choose the correct word: “The loud music did not ___ my concentration.”',a:['affect','effect','past','passed'],c:0,h:'The missing word is the action of influencing something.',e:'“Affect” is used for the influencing action.'},
      {section:9,q:'Which pair are antonyms?',a:['large and huge','happy and joyful','hot and cold','quick and fast'],c:2,h:'Antonyms have opposite meanings.',e:'“Hot” and “cold” are opposites.'}
    ]
  },

  maths: {
    label:'Maths World', icon:'🔢', theme:'maths',
    sections:[
      {title:'Number and Place Value',lesson:'Develop place value with larger numbers, ordering, negative numbers, Roman numerals, decimals and rounding.',topics:['Number Stuff','Ordering Numbers','Negative Numbers','Roman Numerals','Decimals','Rounding','Practice Questions'],explain:'Choose a six-digit number and explain the value of each digit.'},
      {title:'Calculations',lesson:'Use written and mental methods for addition, subtraction, multiplication and division, then extend to powers of ten, money, estimation and number properties.',topics:['Written Adding and Subtracting','Multiplication','Written Multiplication','Division','Written Division','Multiplying by 10, 100 and 1000','Dividing by 10, 100 and 1000','Mental Maths','Order of Operations','Typical Questions','Calculations with Money','Estimation and Accuracy','Multiples','Factors','Prime Numbers','Prime Factors','Square and Cube Numbers','Calculators','Practice Questions'],explain:'Explain the difference between a factor and a multiple.'},
      {title:'Fractions, Decimals and Percentages',lesson:'Work with fractions and their equivalent forms, compare and calculate with fractions, and connect fractions to decimals and percentages.',topics:['Fractions','Equivalent Fractions','Mixed Numbers and Improper Fractions','Comparing Fractions','Multiplying Fractions','Adding and Subtracting Fractions','Dividing Fractions','Equivalent Fractions and Decimals','Division and Fractions','Percentages','Practice Questions'],explain:'Explain why 1/2, 0.5 and 50% represent the same amount.'},
      {title:'Ratio, Proportion and Algebra',lesson:'Study relationships between quantities, percentage problems, similar shapes, symbols, formulae, missing numbers and sequences.',topics:['Ratio and Proportion','Percentage Problems','Similar Shapes','Using Symbols and Letters','Formulae and Expressions','Using Formulae','Finding Missing Numbers','Number Sequences','Practice Questions'],explain:'Give a number sequence and describe its rule.'},
      {title:'Measure',lesson:'Use time and measurement units, convert between units and solve problems involving perimeter, area and volume.',topics:['Time','Units','Conversions','Unit Conversions','Perimeters','Areas','Volume','Practice Questions'],explain:'Explain the difference between perimeter and area.'},
      {title:'Geometry',lesson:'Investigate angles, 2D and 3D shapes, nets, symmetry, coordinates, reflection and translation.',topics:['Angles','Angle Rules','2D Shapes','3D Shapes You Need to Know','Shape Nets','Symmetry','Coordinates','Using Coordinates','Reflection and Translation','Translation','Practice Questions'],explain:'Describe one difference between reflection and translation.'},
      {title:'Statistics',lesson:'Read, present and interpret information using tables, timetables, charts and graphs, and calculate the mean.',topics:['Tables','Timetables','Bar Charts','Pictograms','Line Graphs','Pie Charts','The Mean','Practice Questions','Words You Need to Know'],explain:'Explain how to calculate the mean of four values.'}
    ],
    questions:[
      {section:0,q:'What is the value of the digit 6 in 364,219?',a:['6','600','6,000','60,000'],c:3,h:'Count the place values from the right.',e:'The 6 is in the ten-thousands place, so its value is 60,000.'},
      {section:0,q:'Round 4,738 to the nearest hundred.',a:['4,700','4,800','4,730','5,000'],c:0,h:'Look at the tens digit.',e:'The tens digit is 3, so 4,738 rounds down to 4,700.'},
      {section:1,q:'What is 3,487 + 2,156?',a:['5,543','5,643','5,653','5,743'],c:1,h:'Add each place value carefully.',e:'3,487 + 2,156 = 5,643.'},
      {section:1,q:'Which number is a factor of 36?',a:['5','7','9','11'],c:2,h:'A factor divides 36 exactly.',e:'36 ÷ 9 = 4 exactly, so 9 is a factor.'},
      {section:1,q:'What is 6 × 70?',a:['42','420','4,200','76'],c:1,h:'Think of 70 as 7 tens.',e:'6 × 70 = 42 tens = 420.'},
